### ISSUE TITLE
Keep receiving Please login error with current demo

### ISSUE THREAD

**Issue by sc0Vu** [BingX-API/BingX-swap-api-doc#9]
Hi there,

Thanks for the great api documentation, but I had some questions when integrate private api.

I used my own implementation and example from this repo, the public api works great.

But I couldn't call private api, it always throw `Please login again error`.

```
go run trade_demo.go
queryOpenOrders:
  request: https://open-api.bingx.com/openApi/spot/v1/trade/openOrders?symbol=XRP-USDT&timestamp=1659432645883&signature=MYVALIDSIGNATURE
  response: {"code":100001,"msg":"Please login again","success":false,"timestamp":1659432645968} <nil>
```

BTW, I've contact swap_support many times, and didn't get any reply.
